import React from 'react';

interface GuideProps {
  guide: string;
  crop: string;
}

const CultivationGuide: React.FC<GuideProps> = ({ guide, crop }) => {
  
  // Helper to parse **bold** text into React elements
  const parseBold = (text: string) => {
    // Replace **text** with <strong>text</strong>
    const parts = text.split(/(\*\*[^*]+\*\*)/g);
    return parts.map((part, i) => {
      if (part.startsWith('**') && part.endsWith('**')) {
        const boldText = part.slice(2, -2);
        return <strong key={i} className="text-slate-900 font-bold">{boldText}</strong>;
      }
      return part;
    });
  };

  // Function to format the markdown-like text from Gemini
  const formatText = (text: string) => {
    return text.split('\n').map((line, index) => {
      const trimmedLine = line.trim();

      if (trimmedLine === '---' || trimmedLine === '') {
        return trimmedLine === '' ? <br key={index} /> : null;
      }

      if (trimmedLine.startsWith('###')) {
        const headingText = line.replace(/#/g, '').trim().replace(/\*\*/g, '');
        return <h3 key={index} className="text-xl font-bold text-green-800 mt-6 mb-3">{headingText}</h3>;
      }
      
      // Handle "Key: Value" lines that might start with bolding
      if (trimmedLine.includes(':') && (trimmedLine.startsWith('**') || trimmedLine.startsWith('- **') || trimmedLine.startsWith('* **'))) {
        const cleanLine = trimmedLine.replace(/^[-*] /, ''); // Remove list bullet if present
        const parts = cleanLine.split(':');
        const keyText = parts[0].replace(/\*\*/g, '').trim();
        return (
            <div key={index} className="mb-2">
                <span className="font-bold text-slate-800">{keyText}:</span>
                <span className="text-slate-600 ml-2">{parseBold(parts.slice(1).join(':').trim())}</span>
            </div>
        )
      }

      // Handle standard list items
      if (trimmedLine.startsWith('* ') || trimmedLine.startsWith('- ')) {
        const content = trimmedLine.replace(/^[-*] /, '');
        return <li key={index} className="ml-4 text-slate-700 mb-1 list-disc list-inside">{parseBold(content)}</li>;
      }

      // Default paragraph handling
      return (
        <p key={index} className="text-slate-700 mb-2 leading-relaxed">
            {parseBold(line)}
        </p>
      );
    });
  };

  return (
    <div className="bg-white rounded-xl shadow-lg border border-green-100 overflow-hidden">
      <div className="bg-green-50 px-8 py-6 border-b border-green-100">
        <h2 className="text-2xl font-bold text-green-900 flex items-center gap-3">
          🌱 Cultivation Guide: {crop}
        </h2>
        <p className="text-green-700 mt-1">AI-Generated personalized roadmap for your farm</p>
      </div>
      <div className="p-8">
        <div className="prose prose-green max-w-none">
            {formatText(guide)}
        </div>
        
        <div className="mt-8 p-4 bg-yellow-50 border border-yellow-200 rounded-lg text-sm text-yellow-800 flex items-start gap-3">
            <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 flex-shrink-0" viewBox="0 0 20 20" fill="currentColor">
                <path fillRule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clipRule="evenodd" />
            </svg>
            <p>
                <strong>Disclaimer:</strong> This guide is generated by Artificial Intelligence based on the provided parameters. 
                Always verify with local agricultural experts before making large investments.
            </p>
        </div>
      </div>
    </div>
  );
};

export default CultivationGuide;